name: Export vcpkg Dependencies

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual build'
        required: false
        default: 'Manual dependency update'

env:
  VCPKG_COMMIT_ID: '120deac3062162151622ca4860575a33844ba10b' # Example ID

jobs:
  build-and-export:
    runs-on: windows-latest
    strategy:
      matrix:
        job:
          - vcpkg-triplet: x64-windows-static

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download RustDesk vcpkg.json
        run: |
          curl -L https://raw.githubusercontent.com/rustdesk/rustdesk/master/vcpkg.json -o vcpkg.json
        shell: bash

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg # Using workspace is cleaner for artifacts
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.job.vcpkg-triplet }}
        run: |
          ./vcpkg/vcpkg install \
            --triplet ${{ matrix.job.vcpkg-triplet }} \
            --x-install-root="${{ github.workspace }}/installed"
        shell: bash

      - name: Upload Installed Dependencies
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-export-${{ matrix.job.vcpkg-triplet }}
          path: ${{ github.workspace }}/installed/
          if-no-files-found: error